version: '2'

services:
  web:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
      MYSQL_DATABASE: estoqDB

  php:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1